import turtle

turtle.speed(1000)
turtle.hideturtle()
turtle.penup()
turtle.backward(150)
turtle.left(90)
turtle.forward(100)
turtle.pendown()
turtle.color("#BBDEF0")
turtle.pensize(10)
turtle.penup()
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(30)
turtle.pendown()
turtle.circle(20,180)
turtle.penup()
turtle.backward(5)
turtle.right(90)
turtle.backward(40)
turtle.left(180+90)
turtle.pendown()
#to change right circles difference 
turtle.forward(5)
turtle.circle(20,180)
turtle.forward(10)
turtle.color("#F49F0A")

turtle.right(180)
turtle.circle(20,180)
turtle.backward(10)
turtle.left(90)
turtle.penup()
turtle.forward(40)
turtle.pendown()
turtle.right(270)
turtle.circle(20,180)

turtle.penup()
turtle.left(90)
turtle.forward(40)
turtle.right(90)


turtle.forward(30)
turtle.left(90)
turtle.backward(50)




turtle.left(90)
turtle.pendown()

turtle.left(5)

#turtle.fillcolor("olivedrab")
turtle.fillcolor("#BBDEF0")
turtle.penup()
turtle.begin_fill()
turtle.forward(10)
turtle.right(95)
turtle.forward(100)
turtle.right(95)
turtle.forward(20)
turtle.right(90)
turtle.forward(100)
turtle.left(95)
turtle.end_fill()
turtle.penup()
turtle.forward(7)
turtle.pendown()

turtle.fillcolor("#F75781")
#turtle.fillcolor("teal")
turtle.penup()
turtle.begin_fill()
turtle.left(85)
turtle.forward(98)
turtle.right(95)
turtle.forward(20)
turtle.right(75)
turtle.forward(88)
turtle.right(15+75)
turtle.forward(35)
turtle.left(180)
turtle.end_fill()
turtle.penup()
turtle.forward(43)
turtle.pendown()

turtle.fillcolor("#F49F0A")
#turtle.fillcolor("crimson")
turtle.penup()
turtle.begin_fill()
turtle.forward(15)
turtle.left(85)
turtle.forward(80)
turtle.left(83)
turtle.forward(25)
turtle.left(7+95)
turtle.forward(85)
turtle.end_fill()

turtle.penup()
turtle.forward(5)
turtle.left(90)
turtle.forward(50)
turtle.color("#00A6A6")
turtle.write("Gift",font=("Pressure",16,'bold'))
turtle.forward(3)
turtle.left(90)
turtle.color("#F75781")
turtle.forward(38)
turtle.write("Shop",font=("Pressure",16,'bold'))

turtle.penup()
turtle.color("#F75781")
turtle.goto(50,230)
turtle.write("Login" , font=("Arial" ,20 , 'bold'))

turtle.color("#00A6A6")
turtle.fillcolor("#00A6A6")
turtle.goto(50,210)

turtle.begin_fill()
turtle.pendown()
turtle.left(180)
turtle.circle(18,90)
turtle.right(365)
turtle.forward(300)
turtle.circle(18,90)
turtle.forward(200)
turtle.circle(18,90)
turtle.forward(300)
turtle.circle(18,90)
turtle.forward(200)
turtle.end_fill()

turtle.penup()
turtle.goto(50, 170)
turtle.color('white')
turtle.write("Username or Email" , font = ('Arial' , 10))
turtle.goto(70,160)

turtle.pendown()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.pensize(5)
turtle.circle(15,90)
turtle.right(360)
turtle.forward(5)
turtle.circle(15,90)
turtle.forward(160)
turtle.circle(15,90)
turtle.forward(5)
turtle.circle(15,90)
turtle.forward(160)
turtle.end_fill()
turtle.penup()

turtle.goto(70,152)
turtle.fillcolor("#EFCA08")
turtle.begin_fill()
turtle.circle(4)
turtle.end_fill()

turtle.goto(70, 142)
turtle.fillcolor("#EFCA08")
turtle.begin_fill()
turtle.circle(7,steps = 3)
turtle.end_fill()
turtle.penup()

turtle.goto(80,136)
turtle.color("#EFCA08")
turtle .write("Enter your usernsme or your email" , font= ("Arial" , 7))

turtle.goto(50, 90)
turtle.color('white')
turtle.write("Password" , font = ('Arial' , 10))
turtle.goto(70,80)
turtle.pendown()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.pensize(5)
turtle.circle(15,90)
turtle.right(360)
turtle.forward(5)
turtle.circle(15,90)
turtle.forward(160)
turtle.circle(15,90)
turtle.forward(5)
turtle.circle(15,90)
turtle.forward(160)
turtle.end_fill()
turtle.penup()

turtle.goto(70 ,65)
#turtle.right(180)
turtle.pendown()
turtle.fillcolor("#EFCA08")
turtle.color("#EFCA08")
turtle.right(90)
turtle.circle(3,180)
turtle.pensize(3)
turtle.begin_fill()
turtle.right(90)
turtle.forward(3)
turtle.left(90)
turtle.forward(8)
turtle.left(90)
turtle.forward(12)
turtle.left(90)
turtle.forward(7)
turtle.left(90)
turtle.forward(12)
turtle.end_fill()

turtle.penup()
turtle.goto(84,58)
turtle.color("#EFCA08")
turtle.write("Enter your passward" , font= ("Arial" , 7))

turtle.goto(165,30)
turtle.color("#F49F0A")
turtle.write("forgot my password?" , font= ("Arial" , 6))

turtle.goto(100,10)
turtle.color("#F08700")
turtle.fillcolor("#F08700")
turtle.begin_fill()
turtle.pendown()
turtle.circle(7,80)
turtle.forward(6)
turtle.circle(7,80)
turtle.left(20)
turtle.forward(100)
turtle.circle(7,80)
turtle.forward(6)
turtle.circle(7,80)
turtle.left(20)
turtle.forward(100)
turtle.end_fill()
turtle.penup()

turtle.goto(130,-10)
turtle.color("white")
turtle.write("Login" , font = ("Arial" , 10 , "bold"))

turtle.goto(90,-30)
turtle.write("I don\'t have an acount" , font = ("Arial" , 6))
turtle.goto(165,-30)
turtle.write("|Sign up" , font = ("Arial" , 7 , "bold"))

turtle.goto(100,-50)
turtle.pendown()
turtle.circle(17)
turtle.penup()
turtle.forward(5)
turtle.left(90)
turtle.forward(34)
turtle.write("f" , font = ("Arial" , 20 , "bold") )

turtle.goto(130, -68)
turtle.pendown()
turtle.circle(17)
turtle.penup()
turtle.forward(13)
turtle.left(90)
turtle.forward(6)
turtle.write("G+" , font = ("Arial" , 14 , "bold") )

turtle.forward(58)
turtle.right(35)
turtle.backward(3)

turtle.pendown()
turtle.circle(17)
turtle.penup()
turtle.forward(2)
turtle.write("in" , font = ("Arial" , 14 , "bold") )
''''''

